### ISSUE TITLE
Multisensor setup with SPI Interface - example

### ISSUE THREAD

**Issue by DasSchilli** [stm32duino/VL53L8CX#11]
Hello,

can you provide an example code of interacting with more than one VL53L8CX sensors in SPI mode?

Thank you.

**Comment by cparata** [comment]
Hi @DasSchilli ,
you can give a look at [this example](https://github.com/stm32duino/X-NUCLEO-53L8A1/blob/main/examples/X_NUCLEO_53L8A1_MultiSensorRanging_SPI/X_NUCLEO_53L8A1_MultiSensorRanging_SPI.ino).
Best Regards,
Carlo

**Comment by DasSchilli** [comment]
Thx.
