### ISSUE TITLE
Compilation error with Arduino IDE

### ISSUE THREAD

**Issue by cedrick-f** [stm32duino/VL53L8CX#2]
Hi

I try to compile the example `VL53L8CX_HelloWorld_I2C.ino` into a Nucleo-F401RE board with Arduino IDE (version 2.0.4) on Windows 10 OS, but i get the following error during the compilation :

```
c:/users/xxx/appdata/local/arduino15/packages/stmicroelectronics/tools/xpack-arm-none-eabi-gcc/12.2.1-1.2/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld.exe: C:\Users\Cedrick\AppData\Local\Temp\arduino\sketches\2E654FFD584778FA4B92CD8319F2CC50/VL53L8CX_HelloWorld_I2C.ino.elf section '.rodata' will not fit in region 'FLASH'
c:/users/xxx/appdata/local/arduino15/packages/stmicroelectronics/tools/xpack-arm-none-eabi-gcc/12.2.1-1.2/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld.exe: region 'FLASH' overflowed by 91800 bytes
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1
```

thanks by advance for your help
Cédrick

**Comment by fpistm** [comment]
This simply means you exceed the size of the flash. You can try to reduce your code or to optimize the core. You can refers to the wiki how to do tha.t. anyway maybe I'm surprised as F401RE have 512k flah. Are you sure you select the correct board part number?

**Comment by cedrick-f** [comment]
Among the STM32 MCU based boards, I selected Nucleo-64.
For information, the program compiles well if I choose Nucleo-144 (but of course cant't be uploaded)

**Comment by fpistm** [comment]
You have to select also the part number. Else you build for the first one in the menu which is a C0 with 32k.

**Comment by cedrick-f** [comment]
Thanks !
